// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXT-cvU96og5GmHSYfohMW6QpRaFcS6MY',
    appId: '1:148742212571:android:290183b18385d7a83275fe',
    messagingSenderId: '148742212571',
    projectId: 'fanchat-7db9e',
    databaseURL: 'https://fanchat-7db9e-default-rtdb.firebaseio.com',
    storageBucket: 'fanchat-7db9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCh4EYc2ynRUEid3K4awYg3rkcYpczTSw',
    appId: '1:148742212571:ios:04f585aa60bdbf5d3275fe',
    messagingSenderId: '148742212571',
    projectId: 'fanchat-7db9e',
    databaseURL: 'https://fanchat-7db9e-default-rtdb.firebaseio.com',
    storageBucket: 'fanchat-7db9e.appspot.com',
    androidClientId: '148742212571-714ba1ekn48sildohaul97m0imjkarpv.apps.googleusercontent.com',
    iosClientId: '148742212571-jm877td9o7mh5e80oos7aukvti1psj5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanchat',
  );
}
